### ISSUE TITLE
Archive this repository?

### ISSUE THREAD

**Issue by tswast** [GoogleCloudPlatform/web-docs-samples#14]
These code samples haven't been updated in a while. There aren't many dependencies, but I'm not sure if we're keeping up with them.

As far as I can tell from Code Search, the Endpoints sample *is* used, but the Speech and Vision samples are not.

**Comment by tswast** [comment]
CC @daniel-sanche @navinger

**Comment by daniel-sanche** [comment]
Personally I haven't worked on endpoints in a couple years now, so I'm not sure if they're still using the sample. I think it's probably a good idea to archive this repo, and possibly find a new home for the endpoints sample if it's still needed

**Comment by minherz** [comment]
+1 to archive

**Comment by iennae** [comment]
Before we archive, let's make sure TW is included in this discussion too.

**Comment by meredithslota** [comment]
Agreed. Since the code samples for Cloud Endpoints are used in cloud.google.com, we should find an owner for them or remove them from cloud.google.com before archiving. Assigning to myself in the meantime to try to find owners.
